// components/CrisisSupport.tsx
//
// Content here is deliberately static (see constants/crisisResources.ts) —
// never generated by the LLM. This screen must render instantly the moment
// a safety answer is "yes", without waiting on any network call.

import { Card, CardContent, CardHeader, CardTitle } from "@repo/ui/components/card";
import { Button } from "@repo/ui/components/button";
import { useNavigate } from "react-router";
import { CRISIS_RESOURCES } from "../constants/crisisResources";

interface CrisisSupportProps {
  onContinue: () => void;
}

export function CrisisSupport({ onContinue }: CrisisSupportProps) {
  const navigate = useNavigate();

  return (
    <Card className="rounded-2xl border-orange-200 bg-orange-50/60 shadow-sm">
      <CardHeader>
        <CardTitle className="text-base font-medium text-orange-900">
          You don't have to go through this alone
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <p className="text-sm text-orange-900">
          Thank you for answering honestly. What you're feeling matters, and
          support is available right now — whenever you're ready to reach
          out.
        </p>

        <div className="space-y-3">
          {CRISIS_RESOURCES.map((resource) => (
            <a
              key={resource.name}
              href={resource.href}
              className="block rounded-xl bg-white p-4 shadow-sm transition-colors hover:bg-orange-50"
            >
              <p className="text-sm font-semibold text-slate-800">{resource.name}</p>
              <p className="mt-1 text-xs text-slate-500">{resource.description}</p>
              <p className="mt-2 text-sm font-medium text-teal-700">{resource.contact}</p>
            </a>
          ))}
        </div>

        <Button className="w-full rounded-xl" onClick={() => navigate("/book-appointment")}>
          Book a counsellor appointment
        </Button>

        <button
          type="button"
          onClick={onContinue}
          className="w-full text-center text-xs font-medium text-orange-800 underline underline-offset-2"
        >
          I've noted this — let me finish the remaining questions
        </button>
      </CardContent>
    </Card>
  );
}
